Repository AY2526S1-CS2103T-T13-3/tp, pull requests merged in 2025-10, with the labels that each got.

#51 Edit AboutUs photo
  docs/AboutUs.md
  docs/images/gabrieltang515.png
Labels: type.Task

#50 docs: Update Developer Guide for Cheka's features
  docs/DeveloperGuide.md
Labels: type.Task

#52 feat: Add command to add player to team
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddTeamCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/team/Team.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/storage/JsonAdaptedTeam.java
  src/test/data/JsonAddressBookStorageTest/invalidAndValidPersonAddressBook.json
  src/test/data/JsonAddressBookStorageTest/invalidPersonAddressBook.json
  src/test/data/JsonAddressBookStorageTest/validPersonAndMissingTeamAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/commons/util/SampleDataUtilTest.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddTeamCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/model/team/TeamTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/storage/JsonAdaptedTeamTest.java
  src/test/java/seedu/address/testutil/ModelStub.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TeamBuilder.java
  src/test/java/seedu/address/testutil/TeamUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
  src/test/java/seedu/address/testutil/TypicalTeams.java
Labels: priority.High

#55 docs: Improve DeveloperGuide.md
  docs/DeveloperGuide.md
Labels: type.Task

#57 Update developer guide for Gabriel's features
  docs/DeveloperGuide.md
Labels: type.Task

#58 feat: List teams command
  docs/DeveloperGuide.md
  nonexistent.json
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/commands/ListTeamsCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/TeamCard.java
  src/main/java/seedu/address/ui/TeamListPanel.java
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/TeamListCard.fxml
  src/main/resources/view/TeamListPanel.fxml
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandResultTest.java
  src/test/java/seedu/address/logic/commands/ListTeamsCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/testutil/ModelStub.java
  src/test/java/seedu/address/testutil/StorageManagerStub.java
Labels: priority.Medium

#72 feat: Add gui for player's team
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/Extensions.css
  src/main/resources/view/PersonListCard.fxml
Labels: Priority.Low
